tests = exe{test_golden test_harness test_report test_stages}

exe{test_golden}: c{test_golden} ../../src/liba{certifiable_harness}
exe{test_harness}: c{test_harness} ../../src/liba{certifiable_harness}
exe{test_report}: c{test_report} ../../src/liba{certifiable_harness}
exe{test_stages}: c{test_stages} ../../src/liba{certifiable_harness}

$tests:
{
  c.coptions += -UNDEBUG
  c.libs += -lm
  test = true
}

./: $tests
